/*
 * Copyright (C) 2017 Laboratory of Experimental Biophysics
 * Ecole Polytechnique Federale de Lausanne
 * 
 * Author: Marcel Stefko
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ch.epfl.leb.alica.controllers.inverter;

import ch.epfl.leb.alica.controllers.ControllerRealtimeControlPanel;
import ij.IJ;

/**
 *
 * @author stefko
 */
public class InverterRealtimeControlPanel extends ControllerRealtimeControlPanel {
    private final InvertController controller;
    /**
     * Creates new form InverterRealtimeControlPanel
     */
    public InverterRealtimeControlPanel(InvertController controller) {
        this.controller = controller;
        initComponents();
        l_value_at_1mw.setText(String.format("%5.2f", controller.getValueAt1Mw()));
        this.setBounds(5,5,160,150);
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        e_new_value_at_1mw = new javax.swing.JTextField();
        l_value_at_1mw = new javax.swing.JLabel();
        b_set = new javax.swing.JButton();

        jLabel1.setText("Value at 1mw:");

        e_new_value_at_1mw.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        e_new_value_at_1mw.setText("0.0");

        l_value_at_1mw.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        l_value_at_1mw.setText("0.0");

        b_set.setText("Set");
        b_set.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_setMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_set)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(e_new_value_at_1mw, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(l_value_at_1mw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_value_at_1mw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(e_new_value_at_1mw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(b_set)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_setMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_setMouseClicked
        double new_val;
        try {
            new_val = Double.parseDouble(e_new_value_at_1mw.getText());
        } catch (NumberFormatException ex) {
            IJ.showMessage("Wrong number format.");
            return;
        }
        l_value_at_1mw.setText(e_new_value_at_1mw.getText());
        controller.setValueAt1Mw(new_val);
    }//GEN-LAST:event_b_setMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_set;
    private javax.swing.JTextField e_new_value_at_1mw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l_value_at_1mw;
    // End of variables declaration//GEN-END:variables
}
