/*
 * Copyright (C) 2017 Laboratory of Experimental Biophysics
 * Ecole Polytechnique Federale de Lausanne
 * 
 * Author: Marcel Stefko
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ch.epfl.leb.alica.analyzers.spotcounter;

import ch.epfl.leb.alica.analyzers.AnalyzerStatusPanel;
import ij.IJ;

/**
 * Status panel of SpotCounter, enables modification of threshold in real time.
 * @author Marcel Stefko
 */
public class SpotCounterStatusPanel extends AnalyzerStatusPanel {
    private final SpotCounterCore core;
    
    /**
     * Creates new form SpotCounterStatusPanel
     * @param core SpotCounterCore
     */
    public SpotCounterStatusPanel(SpotCounterCore core) {
        initComponents();
        this.core = core;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        e_noise_tolerance = new javax.swing.JTextField();
        e_box_size = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b_set = new javax.swing.JButton();

        jLabel1.setText("SpotCounter");

        jLabel2.setText("Noise tolerance:");

        e_noise_tolerance.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        e_noise_tolerance.setText("80");

        e_box_size.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        e_box_size.setText("5");

        jLabel3.setText("Box size:");

        b_set.setText("Set");
        b_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_setActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_box_size, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(e_noise_tolerance, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(b_set)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(e_noise_tolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_box_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(b_set)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_setActionPerformed
        int noise_tolerance = Integer.parseInt(e_noise_tolerance.getText());
        int box_size = Integer.parseInt(e_box_size.getText());
        
        if (noise_tolerance<1 || box_size<1) {
            IJ.showMessage("Wrong parameters for SpotCounter!");
            return;
        }
        
        core.setParams(noise_tolerance, box_size);
    }//GEN-LAST:event_b_setActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_set;
    private javax.swing.JTextField e_box_size;
    private javax.swing.JTextField e_noise_tolerance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
